# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1bc72f7e8afce5570e94783d2bd59a17cd955880526c14c40fbb798cb7a5a1f8506a333157303a0bc0661251fc7fc67aa022c2849201ca3745f7a51dbc56d99

test:
  secret_key_base: a1bc72f7e8afce5570e94783d2bd59a17cd955880526c14c40fbb798cb7a5a1f8506a333157303a0bc0661251fc7fc67aa022c2849201ca3745f7a51dbc56d99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a1bc72f7e8afce5570e94783d2bd59a17cd955880526c14c40fbb798cb7a5a1f8506a333157303a0bc0661251fc7fc67aa022c2849201ca3745f7a51dbc56d99
